spring.application.name=mySpringAi
################ Log 相關設定 ################
# Log formate: green = 時間 / blue = log等級 / red = thread名稱 / yellow = log名稱 / white = log內容
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
################ LLM model OpenAI 相關設定 ################
# OpenAI api key
spring.ai.openai.api-key=${OPENAI_API_KEY}
# OpenAI-model type
spring.ai.openai.chat.model=gpt-4.1-nano
################ LLM model Ollama 相關設定 ################
# Ollama-model type: spring.ai.ollama.base-url 預設是 http://localhost:11434 連到本機的 Ollama server
spring.ai.ollama.chat.model=llama3.2:1b
# Enable DEBUG logging for SimpleLoggerAdvisor
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG
# AUTO_SERVER=true 多個連線同時存取同一個 H2 檔案 Spring Boot app + H2 Console + DataGrip
spring.datasource.url=jdbc:h2:file:./chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
# 啟用 H2 Console
spring.h2.console.enabled=true
# 讓 Spring AI「自動執行內建 schema-h2.sql（或其他 dialect schema）」來建立資料表
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
# 因為 Qdrant 是用 Spring Boot 自動啟動的，如果不用 down，container 會殘留，導致：占用 port（6333/6334）
spring.docker.compose.stop.command=down
# 當 Spring Boot 啟動時，若 Qdrant 的 collection 不存在，就會「自動建立 schema」
spring.ai.vectorstore.qdrant.initialize-schema=true
# Spring AI 要連線的 Qdrant 主機名稱
spring.ai.vectorstore.qdrant.host=localhost
# 所以 Spring AI 用 gRPC client 去連 Qdrant
spring.ai.vectorstore.qdrant.port=6334
# 我希望所有 RAG 的向量資料都存進 Qdrant 的 rag-collection 這個 collection，同一個 Qdrant 伺服器可以給很多模型用，但每個模型必須用自己的 Collection（向量維度必須一致）。
spring.ai.vectorstore.qdrant.collection-name=rag-collection
# Hibernate：啟動時，自動「更新資料庫結構」以符合你的 Entity 定義，但「不刪資料」
spring.jpa.hibernate.ddl-auto=update
# Stdio (標準輸入輸出) 模式: Spring Boot 會在後台直接啟動一個新的進程（Process），透過電腦內部的管道（Standard I/O）跟它說話。這通常用於你電腦本機安裝的工具。
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
# SSE (Server-Sent Events) 模式 - 其中一個transport type 可能要comment for testing * AND IT HAS TO BE RUNNING FIRST
spring.ai.mcp.client.sse.connections.remoteMCP.url=http://localhost:8081
# both stdio + sse will be registered in ToolCallbackProvider
# 只允許透過 Web（HTTP）存取 health 與 metrics 這兩個 Actuator (health → 我還活著嗎？) endpoint (metrics → 我跑得好嗎？)
management.endpoints.web.exposure.include=health, metrics


